const Config = require('../config/const');

module.exports = [
    {lang: 'en', intent: 'cmd_enable_learn',  p:`enable learn`},
    {lang: 'en', intent: 'cmd_disable_learn',  p:`disable learn`},
    {lang: 'en', intent: 'greet_me',  p:`(?<botname>${Config.BOT_NAME})`},
    
    {lang: 'en', intent: 'res_location',  p:'.*lat (?<lat>.*) lon (?<lon>.*).*'},

    {lang: 'en', intent: 'greet_me',  p:`(hi|hello)(?<botname>${Config.BOT_NAME})`},
    {lang: 'th', intent: 'greet_me',  p:`(สวัสดี|หวัดดี|ว่าไง)(?<botname>${Config.BOT_NAME})`},
    {lang: 'en', intent: 'greet_normal',  p:'(hi|hello)'},
    {lang: 'th', intent: 'greet_normal',  p:'(สวัสดี|หวัดดี|ว่าไง)'},
    {lang: 'th', intent: 'greet_pos',  p:'^(เจ๋ง|เยี่ยม|ดี|เก่ง*?)'},
    {lang: 'th', intent: 'greet_neg',  p:'^(โง่|แย่|ไม่ได้เรื่อง|ห่วย*?)'},
    {lang: 'en', intent: 'greet_pos',  p:'^(good|great*?)'},
    {lang: 'en', intent: 'greet_neg',  p:'^(stupid|bad*?)'},

    {lang: 'th', intent: 'common_reject',  p:'^ไม่เอา$'},
    {lang: 'th', intent: 'common_ok',  p:'(โอเค|ขอบคุณ)'},
    {lang: 'en', intent: 'common_ok',  p:'(thanks|ok)'},
    {lang: 'th', intent: 'common_change',  p:'เปลี่ยนเป็น(?<obj>.*)'},
    {lang: 'th', intent: 'common_here',  p:'^แถวนี้$'},
    {lang: 'th', intent: 'common_where',  p:'^(ที่|ใน|แถว|ใกล้)(?<where>.*)'},

    {lang: 'en', intent: 'word_meaning',  p:'^(?<word>.*?) mean.*'},
    {lang: 'en', intent: 'word_pronounce',  p:'^.*say (?<word>.*)'},

    {lang: 'th', intent: 'res_change',  p:'(เปลี่ยนร้าน|ร้านอื่น|ร้านใหม่)'},
    {lang: 'th', intent: 'res_any_near', p:'^อยากกิน(?<any>อะไร)?(อร่อย|ก็ได้)?(?<near>แถวนี้|ใกล้)$'},
    {lang: 'th', intent: 'res_foodtype_near',  p:'^อยากกินอาหาร(?<foodtype>.*)(?<near>แถวนี้|ใกล้)$'},
    {lang: 'th', intent: 'res_foodtype_where',  p:'^อยากกินอาหาร(?<foodtype>.*)(ที่|ใน|แถว|ใกล้)(?<where>.*)$'},
    {lang: 'th', intent: 'res_food_near',  p:'^อยากกิน(?<food>.*)(?<near>แถวนี้|ใกล้)$'},
    {lang: 'th', intent: 'res_food_where',  p:'^อยากกิน(?<food>.*).*(แถว|ใกล้|ใน)(?<where>.*)'},
    {lang: 'th', intent: 'res_any_recommend',  p:'^อยากกิน(?<any>อะไร).*แนะนำ.*'},
    {lang: 'th', intent: 'res_greet',  p:'หิว.*'},
    {lang: 'th', intent: 'res_ig_price',  p:'(ไม่สนราคา|ไม่เอาราคา|เท่าไหร่ก็ได้)'},
    {lang: 'th', intent: 'res_cancel',  p:'ไม่กิน(แล้ว)?'},
    {lang: 'th', intent: 'res_cheap',  p:'ราคาไม่เกิน(?<maxPrice>.*)?'},
    {lang: 'th', intent: 'res_cheap',  p:'ราคาต่ำกว่า(?<maxPrice>.*)?'},
    {lang: 'th', intent: 'res_cheap',  p:'(ราคา)*?แพง(ไป)*?'},
    {lang: 'th', intent: 'res_exp',  p:'ราคามากกว่า(?<minPrice>.*)?'},
    {lang: 'th', intent: 'res_exp',  p:'ราคาสูงกว่า(?<minPrice>.*)?'},
    {lang: 'th', intent: 'res_exp',  p:'(ราคา)*?ถูก(ไป)*?'},
    {lang: 'th', intent: 'res_any',  p:'^กิน(อะ)?ไรดี.*$'},
    {lang: 'th', intent: 'res_any',  p:'^อยากกิน(?<any>อะไร).*'},
    {lang: 'th', intent: 'res_any',  p:'^เบื่อ.*(?<any>อะไร).*'},
    {lang: 'th', intent: 'res_food_recommend',  p:'^อยากกิน(?<food>.*).*แนะนำ.*'},
    {lang: 'th', intent: 'res_foodtype',  p:'^ร้านอาหาร(?<foodtype>.*?)(แถวนี้)?(ให้)?(หน่อย)?$'}, 
    {lang: 'th', intent: 'res_foodtype',  p:'^แนะนำ(ร้าน)?อาหาร(?<foodtype>.*?)(แถวนี้)?(ให้)?(หน่อย)?$'},
    {lang: 'th', intent: 'res_foodtype',  p:'^ร้าน(ที่)?ขายอาหาร(?<foodtype>.*?)(แถวนี้)?(ให้)?(หน่อย)?$'},
    {lang: 'th', intent: 'res_food',  p:'^ร้าน(ที่)?ขาย(?<food>.*?)(แถวนี้)?(ให้)?(หน่อย)?$'},
    {lang: 'th', intent: 'res_food',  p:'^แนะนำ(?!ร้าน|อาหาร)(?<food>.*?)(แถวนี้)?(ให้)?(หน่อย)?$'},
    {lang: 'th', intent: 'res_any',  p:'^แนะนำ?.*$'},
    {lang: 'th', intent: 'res_name',  p:'^(ข้อมูล)?ร้าน(?<resname>.*)$'},
    {lang: 'th', intent: 'res_foodtype',  p:'^อยากกินอาหาร(?<foodtype>.*)$'},
    {lang: 'th', intent: 'res_foodtype',  p:'^อาหาร(?<foodtype>.*)$'},
    {lang: 'th', intent: 'res_foodtype',  p:'^.*ถ้า.*อาหาร(?<foodtype>.*)$'},
    {lang: 'th', intent: 'res_any_where',  p:'^.*ถ้า.*(ที่|ใน|แถว|ใกล้)(?<where>.*)$'},
    {lang: 'th', intent: 'res_food',  p:'^.*ถ้า(เป็น)?(?<food>.*)$'},
    {lang: 'th', intent: 'res_food',  p:'^กิน(?<food>.*)$'},
    {lang: 'th', intent: 'res_food',  p:'^.*มี(?<food>.*?)(?:ขาย)*?(?:มะ|ไหม)$'},
    {lang: 'th', intent: 'res_any_where',  p:'^มี(อะ)?ไรกิน(ที่|ใน|แถว|ใกล้)(?<where>.*)$'},
    {lang: 'th', intent: 'res_any_where',  p:'^.*(อยู่|มา)(ที่|ใน|แถว|ใกล้)*(?<where>.*)กิน(อะ)?ไร.*$'},
    {lang: 'th', intent: 'res_foodtype_where',  p:'^.*(อยู่|มา)(ที่|ใน|แถว|ใกล้)?(?<where>.*)อยากกินอาหาร(?<foodtype>.*)'},
    {lang: 'th', intent: 'res_food_where',  p:'^(อยู่|มา)(ที่|ใน|แถว|ใกล้)?(?<where>.*?)อยากกิน(?<food>.*)'},
    {lang: 'th', intent: 'res_food',  p:'.*อยากกิน(?<food>.*)$'},

]